name: wiscom
dependencies:
  - python= 3.7
  - jupyter = 1.0
  - matplotlib = 3.4
  - numpy = 1.19
  - pandas = 1.3
  - scipy = 1.6
  - scikit-learn =1.0
  - seaborn = 0.11
  - tqdm = 4.62
  - pip = 21.2
  - pip:
     - mwparserfromhell == 0.6.4
     - urlextract == 1.8.0
     - tldextract == 3.4.3
     - pyspark == 3.2.1
     - networkx == 2.6.3
  - freetype = 2.10.4
